export default {
  id: 'redis.get_memory_info',
  version: '1.0.0',
  lifecycle: 'ACTIVE',
  connector: 'redis-infra',
  category: 'infrastructure',
  displayName: 'Get Redis Memory Info',
  description: 'Returns Redis memory usage metrics including used memory, peak, fragmentation ratio, and eviction policy. Used in monitoring workflows and incident investigation.',
  icon: 'cpu',
  tags: ['redis', 'memory', 'monitoring', 'metrics', 'ops'],
  riskLevel: 'LOW',
  approvalPolicy: {
    required: false, minimumApprovers: 0, eligibleRoles: ['MEMBER'],
    timeoutHours: 0, selfApprovalAllowed: true, notifyOnCreate: false, notifyOnResolve: false,
  },
  requiredPermissions: ['MEMBER'],
  requiredScopes: ['redis:info'],
  executionMode: 'SYNC',
  estimatedDurationMs: 500,
  timeoutMs: 5000,
  retryStrategy: {
    maxAttempts: 3, backoffType: 'EXPONENTIAL', initialDelayMs: 500, maxDelayMs: 4000,
    jitterPercent: 10, retryOn: ['TIMEOUT'], noRetryOn: ['UNAUTHORIZED', 'CONNECTION_FAILED'],
  },
  rollbackStrategy: { supported: false, type: 'NONE', description: 'Read-only — no rollback needed.', requiresApproval: false },
  verificationStrategy: { type: 'IMMEDIATE', successCondition: '$.usedMemory != null' },
  requiredInputs: [],
  optionalInputs: [],
  outputSchema: {
    type: 'object',
    properties: {
      usedMemory:            { type: 'string' },
      usedMemoryRss:         { type: 'string' },
      usedMemoryPeak:        { type: 'string' },
      maxMemory:             { type: 'string' },
      memFragmentationRatio: { type: 'string' },
      evictionPolicy:        { type: 'string' },
      checkedAt:             { type: 'string' },
    },
  },
  auditMetadata: {
    resourceType: 'redis_instance', resourceIdField: null, actionVerb: 'read',
    sensitivityLevel: 'INTERNAL', retainForDays: 90, complianceTags: ['SOC2'],
  },
  telemetryMetadata: {
    eventName: 'action.redis.get_memory_info',
    successMetric: 'flow.action.redis.get_memory_info.success',
    failureMetric: 'flow.action.redis.get_memory_info.failure',
    durationMetric: 'flow.action.redis.get_memory_info.duration_ms',
    dimensions: ['connector', 'workspace_id'],
  },
  relatedActions: ['redis.trigger_bgsave', 'redis.flush_cache'],
};
