export default {
  id: 'redis.trigger_bgsave',
  version: '1.0.0',
  lifecycle: 'ACTIVE',
  connector: 'redis-infra',
  category: 'infrastructure',
  displayName: 'Trigger Redis BGSAVE',
  description: 'Triggers an asynchronous background save of the Redis dataset to disk. Used before maintenance operations to ensure recent data is persisted.',
  icon: 'save',
  tags: ['redis', 'bgsave', 'persistence', 'maintenance', 'backup'],
  riskLevel: 'LOW',
  approvalPolicy: {
    required: false, minimumApprovers: 0, eligibleRoles: ['ADMIN'],
    timeoutHours: 0, selfApprovalAllowed: true, notifyOnCreate: false, notifyOnResolve: false,
  },
  requiredPermissions: ['ADMIN'],
  requiredScopes: ['redis:bgsave'],
  executionMode: 'ASYNC',
  estimatedDurationMs: 5000,
  timeoutMs: 120000,
  retryStrategy: {
    maxAttempts: 2, backoffType: 'FIXED', initialDelayMs: 10000, maxDelayMs: 10000,
    jitterPercent: 0, retryOn: ['TIMEOUT'], noRetryOn: ['UNAUTHORIZED', 'SAVE_IN_PROGRESS'],
  },
  rollbackStrategy: { supported: false, type: 'NONE', description: 'Background save is additive — no rollback needed.', requiresApproval: false },
  verificationStrategy: { type: 'IMMEDIATE', successCondition: '$.triggered == true' },
  requiredInputs: [],
  optionalInputs: [],
  outputSchema: {
    type: 'object',
    properties: {
      triggered:    { type: 'boolean' },
      triggeredAt:  { type: 'string' },
      lastSaveUnix: { type: 'number' },
    },
  },
  auditMetadata: {
    resourceType: 'redis_instance', resourceIdField: null, actionVerb: 'bgsave-triggered',
    sensitivityLevel: 'INTERNAL', retainForDays: 365, complianceTags: ['SOC2'],
  },
  telemetryMetadata: {
    eventName: 'action.redis.trigger_bgsave',
    successMetric: 'flow.action.redis.trigger_bgsave.success',
    failureMetric: 'flow.action.redis.trigger_bgsave.failure',
    durationMetric: 'flow.action.redis.trigger_bgsave.duration_ms',
    dimensions: ['connector', 'workspace_id'],
  },
  relatedActions: ['redis.get_memory_info', 'redis.flush_cache'],
};
