/**
 * Canonical event names for the Universal Workflow Runtime.
 * Used by RuntimeEngine (emit), StepExecutor (emit), and UI clients (subscribe).
 */

export const WorkflowEvent = Object.freeze({
  // Lifecycle
  STARTED:            'WORKFLOW_STARTED',
  PAUSED:             'WORKFLOW_PAUSED',
  RESUMED:            'WORKFLOW_RESUMED',
  COMPLETED:          'WORKFLOW_COMPLETED',
  FAILED:             'WORKFLOW_FAILED',
  CANCELLED:          'WORKFLOW_CANCELLED',

  // Step lifecycle
  STEP_STARTED:       'WORKFLOW_STEP_STARTED',
  STEP_COMPLETED:     'WORKFLOW_STEP_COMPLETED',
  STEP_FAILED:        'WORKFLOW_STEP_FAILED',
  STEP_SKIPPED:       'WORKFLOW_STEP_SKIPPED',
  STEP_RETRYING:      'WORKFLOW_STEP_RETRYING',

  // Approval
  APPROVAL_REQUESTED: 'WORKFLOW_APPROVAL_REQUESTED',
  APPROVAL_RESOLVED:  'WORKFLOW_APPROVAL_RESOLVED',

  // Runtime internals (for monitoring / recovery)
  CHECKPOINT:         'WORKFLOW_CHECKPOINT',
  RECOVERED:          'WORKFLOW_RECOVERED',

  // Phase 9 — Long-running orchestration events
  WAIT_REGISTERED:        'WORKFLOW_WAIT_REGISTERED',
  WAIT_RESOLVED:          'WORKFLOW_WAIT_RESOLVED',
  WAIT_EXPIRED:           'WORKFLOW_WAIT_EXPIRED',
  TIMER_SCHEDULED:        'WORKFLOW_TIMER_SCHEDULED',
  TIMER_FIRED:            'WORKFLOW_TIMER_FIRED',
  CALLBACK_REGISTERED:    'WORKFLOW_CALLBACK_REGISTERED',
  COMPENSATION_STARTED:   'WORKFLOW_COMPENSATION_STARTED',
  COMPENSATION_COMPLETED: 'WORKFLOW_COMPENSATION_COMPLETED',
  COMPENSATION_FAILED:    'WORKFLOW_COMPENSATION_FAILED',
  STALLED:                'WORKFLOW_STALLED',
  ESCALATION:             'WORKFLOW_ESCALATION',
});
