export default {
  id: 'jira.create_issue',
  version: '1.0.0',
  lifecycle: 'ACTIVE',
  connector: 'jira',
  category: 'project',
  displayName: 'Create Jira Issue',
  description: 'Creates a new issue (story, bug, task, epic) in a Jira project.',
  icon: 'plus-circle',
  tags: ['jira', 'issue', 'ticket', 'bug', 'story', 'task', 'create', 'project'],
  riskLevel: 'LOW',
  approvalPolicy: {
    required: false, minimumApprovers: 0, eligibleRoles: ['MEMBER'],
    timeoutHours: 0, selfApprovalAllowed: true, notifyOnCreate: false, notifyOnResolve: false,
  },
  requiredPermissions: ['MEMBER'],
  requiredScopes: ['write:jira-work'],
  executionMode: 'SYNC',
  estimatedDurationMs: 2000,
  timeoutMs: 15000,
  retryStrategy: {
    maxAttempts: 3, backoffType: 'EXPONENTIAL', initialDelayMs: 1000, maxDelayMs: 8000,
    jitterPercent: 10, retryOn: ['RATE_LIMIT', 'TIMEOUT'], noRetryOn: ['PROJECT_NOT_FOUND', 'UNAUTHORIZED', 'INVALID_ISSUE_TYPE'],
  },
  rollbackStrategy: {
    supported: true, type: 'COMPENSATING', compensatingActionId: 'jira.close_issue',
    description: 'Close (and optionally delete) the created issue.', requiresApproval: false,
  },
  verificationStrategy: { type: 'IMMEDIATE', successCondition: '$.id != null' },
  requiredInputs: [
    { name: 'projectKey', type: 'string', description: 'Jira project key', example: 'HPLT' },
    { name: 'title',      type: 'string', maxLength: 255, description: 'Issue summary / title', example: 'Customer complaint: auth timeout on login' },
    { name: 'issueType',  type: 'enum', enum: ['Bug', 'Story', 'Task', 'Epic', 'Subtask'], description: 'Issue type' },
  ],
  optionalInputs: [
    { name: 'description', type: 'string', maxLength: 32767, description: 'Issue description' },
    { name: 'priority',    type: 'enum', enum: ['Highest', 'High', 'Medium', 'Low', 'Lowest'], description: 'Issue priority' },
    { name: 'assignee',   type: 'string', description: 'Assignee name or account ID' },
    { name: 'labels',     type: 'array', items: { name: 'label', type: 'string', description: 'Label text' }, description: 'Labels' },
    { name: 'dueDate',    type: 'string', description: 'Due date (YYYY-MM-DD)', example: '2026-08-15' },
  ],
  outputSchema: {
    type: 'object',
    description: 'Created Jira issue',
    properties: {
      id:         { type: 'string', description: 'Internal issue ID' },
      key:        { type: 'string', description: 'Issue key (e.g. HPLT-205)', example: 'HPLT-205' },
      title:      { type: 'string', description: 'Issue summary' },
      status:     { type: 'string', description: 'Initial status (To Do)' },
      assignee:   { type: 'string', description: 'Assigned user' },
    },
  },
  auditMetadata: {
    resourceType: 'jira_issue', resourceIdField: 'projectKey', actionVerb: 'created',
    sensitivityLevel: 'INTERNAL', retainForDays: 365, complianceTags: ['SOC2'],
  },
  telemetryMetadata: {
    eventName: 'action.jira.create_issue',
    successMetric: 'flow.action.jira.create_issue.success',
    failureMetric: 'flow.action.jira.create_issue.failure',
    durationMetric: 'flow.action.jira.create_issue.duration_ms',
    dimensions: ['connector', 'workspace_id', 'issueType'],
  },
  relatedActions: ['jira.assign_issue', 'jira.transition_issue', 'jira.create_subtask'],
};
