export function generateAgentBoilerplate({
  id,
  name,
  domains    = ['general'],
  description = `${name} agent for FLOW OS`,
  author      = 'Your Name',
}) {
  const pkgId   = `com.${id.toLowerCase().replace(/[^a-z0-9]/g, '.')}.agent-pack`;
  const agentId = `ext.${id.toLowerCase().replace(/[^a-z0-9]/g, '.')}`;

  const manifest = {
    id:                 pkgId,
    name:               `${name} Agent Pack`,
    version:            '0.1.0',
    author,
    description,
    category:           'agent_pack',
    license:            'MIT',
    permissions:        ['agents.register', 'memory.read', 'graph.read'],
    minimumFlowVersion: '14.0.0',
    dependencies:       {},
    entrypoints:        { main: 'main.js' },
    routes:             [],
    actions:            [],
    events:             [],
    agents:             [agentId],
    widgets:            [],
    migrations:         [],
    tags:               ['agent', ...domains],
  };

  const mainJs = `// ${name} Agent Pack — generated by FLOW Extension CLI
// Your agent is registered into the FLOW Cognitive Brain at enable time.

const { BaseAgentPack } = FlowSDK;

class ${_toPascalCase(name)}Agent {
  constructor(config) {
    this.config = config;
    this.id     = '${agentId}';
    this.name   = '${name}';
    this.domains = ${JSON.stringify(domains)};
  }

  /**
   * Analyze the context and return a finding.
   * @param {object} context — { question, retrievedContext, workspaceId, sessionId }
   * @returns {{ finding: string, evidence: object[], confidence: number }}
   */
  async analyze(context) {
    // TODO: implement domain-specific analysis
    const { question } = context;
    return {
      finding:    \`${name} analysis for: \${question}\`,
      evidence:   [],
      confidence: 50,
      domain:     '${domains[0]}',
    };
  }

  /**
   * Heuristic fallback — returns a structured finding without LLM calls.
   */
  heuristicFallback(context) {
    return {
      finding:    \`[${name} heuristic] No data available for: \${context.question}\`,
      evidence:   [],
      confidence: 10,
      domain:     '${domains[0]}',
    };
  }
}

class ${_toPascalCase(name)}AgentPack extends BaseAgentPack {
  agentDefinitions() {
    return [
      {
        id:         '${agentId}',
        name:       '${name}',
        domains:    ${JSON.stringify(domains)},
        AgentClass: ${_toPascalCase(name)}Agent,
        config:     {},
      },
    ];
  }
}

module.exports = { default: ${_toPascalCase(name)}AgentPack };
`;

  return { manifest, files: { 'manifest.json': JSON.stringify(manifest, null, 2), 'main.js': mainJs } };
}

function _toPascalCase(str) {
  return str.replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase())
    .replace(/^./, c => c.toUpperCase());
}
