/**
 * ConnectorBoilerplate — generates a starter connector extension package.
 *
 * Outputs a manifest.json and a main.js that subclasses BaseConnectorPack
 * and registers a skeleton BaseAdapter implementation.
 */
export function generateConnectorBoilerplate({
  id,
  name,
  connectorId,
  authStrategy = 'oauth2',
  description  = `${name} connector for FLOW OS`,
  author       = 'Your Name',
}) {
  const manifest = {
    id:                 `com.${id.toLowerCase().replace(/[^a-z0-9]/g, '.')}.connector`,
    name:               `${name} Connector`,
    version:            '0.1.0',
    author,
    description,
    category:           'connector',
    license:            'MIT',
    permissions:        ['events.write', 'graph.write', 'connectors.read'],
    minimumFlowVersion: '14.0.0',
    dependencies:       {},
    entrypoints:        { main: 'main.js' },
    routes:             [],
    actions:            [],
    events:             [],
    agents:             [],
    widgets:            [],
    migrations:         [],
    tags:               [connectorId.toLowerCase()],
  };

  const mainJs = `// ${name} Connector — generated by FLOW Extension CLI
// Extend BaseConnectorPack and implement your adapter below.

const { BaseConnectorPack } = FlowSDK;

class ${_toPascalCase(name)}Adapter {
  constructor(config) {
    this.config = config;
    this.id = '${connectorId}';
    this.name = '${name}';
    this.authStrategy = '${authStrategy}';
    this.capabilities = ['communication'];
    this.supportedActions = [];
  }

  async healthCheck() {
    return { status: 'HEALTHY', message: '${name} adapter ready' };
  }

  // TODO: implement executeAction, search, and OAuth methods
  async executeAction(action, params, credentials) {
    throw new Error(\`Action "\${action}" not implemented yet\`);
  }

  async initiateAuth(callbackUrl, workspaceId) {
    // Return { url: '<oauth-consent-url>' }
    throw new Error('initiateAuth not implemented yet');
  }

  async exchangeCode(code, workspaceId) {
    // Exchange OAuth code for tokens, store via this.config.authManager
    throw new Error('exchangeCode not implemented yet');
  }
}

class ${_toPascalCase(name)}ConnectorPack extends BaseConnectorPack {
  connectorDefinitions() {
    return [
      {
        id:           '${connectorId}',
        AdapterClass: ${_toPascalCase(name)}Adapter,
        config:       {},
      },
    ];
  }
}

module.exports = { default: ${_toPascalCase(name)}ConnectorPack };
`;

  return { manifest, files: { 'manifest.json': JSON.stringify(manifest, null, 2), 'main.js': mainJs } };
}

function _toPascalCase(str) {
  return str.replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase())
    .replace(/^./, c => c.toUpperCase());
}
