export function generateWidgetBoilerplate({
  id,
  name,
  category   = 'metric',
  size        = 'md',
  endpoint    = '/api/executive/health',
  refreshSeconds = 60,
  description = `${name} dashboard widget`,
  author       = 'Your Name',
}) {
  const pkgId    = `com.${id.toLowerCase().replace(/[^a-z0-9]/g, '.')}.widget`;
  const widgetId = `${pkgId}.main`;

  const manifest = {
    id:                 pkgId,
    name:               `${name} Widget`,
    version:            '0.1.0',
    author,
    description,
    category:           'dashboard_widget',
    license:            'MIT',
    permissions:        ['widgets.register', 'events.read', 'executive.read'],
    minimumFlowVersion: '14.0.0',
    dependencies:       {},
    entrypoints:        { main: 'main.js', frontend: 'widget.jsx' },
    routes:             [],
    actions:            [],
    events:             [],
    agents:             [],
    widgets:            [widgetId],
    migrations:         [],
    tags:               ['widget', category],
  };

  const mainJs = `// ${name} Widget Pack — generated by FLOW Extension CLI
const { BaseWidgetPack } = FlowSDK;

class ${_toPascalCase(name)}WidgetPack extends BaseWidgetPack {
  widgetDefinitions() {
    return [
      {
        id:           '${widgetId}',
        name:         '${name}',
        description:  '${description}',
        category:     '${category}',
        size:         '${size}',
        dataSourceSpec: {
          endpoint:       '${endpoint}',
          refreshSeconds: ${refreshSeconds},
          permissions:    ['executive.read'],
        },
        componentPath: 'widget.jsx',
      },
    ];
  }
}

module.exports = { default: ${_toPascalCase(name)}WidgetPack };
`;

  const widgetJsx = `// ${name} Widget — React component
// This file is loaded by the FLOW Widget SDK on the frontend.
// FlowWidget, useWidgetData, and React are injected globals.

function ${_toPascalCase(name)}Widget({ data, loading, error }) {
  if (loading) return <FlowWidget.Skeleton />;
  if (error)   return <FlowWidget.Error message={error.message} />;

  return (
    <FlowWidget.Card title="${name}">
      <pre>{JSON.stringify(data, null, 2)}</pre>
    </FlowWidget.Card>
  );
}

FlowWidget.register('${widgetId}', ${_toPascalCase(name)}Widget);
`;

  return {
    manifest,
    files: {
      'manifest.json': JSON.stringify(manifest, null, 2),
      'main.js':       mainJs,
      'widget.jsx':    widgetJsx,
    },
  };
}

function _toPascalCase(str) {
  return str.replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase())
    .replace(/^./, c => c.toUpperCase());
}
