export function generateWorkflowBoilerplate({
  id,
  name,
  description = `${name} workflow`,
  connectors  = [],
  steps       = [],
  author      = 'Your Name',
}) {
  const pkgId   = `com.${id.toLowerCase().replace(/[^a-z0-9]/g, '.')}.workflow-pack`;
  const wfId    = id.toLowerCase().replace(/[^a-z0-9]/g, '-');

  const defaultSteps = steps.length ? steps : [
    { id: 'step_1', action: 'connector.action.name', connector: connectors[0] || 'flow', params: {} },
    { id: 'step_2', action: 'flow.notifications.send', connector: 'flow', params: {} },
  ];

  const manifest = {
    id:                 pkgId,
    name:               `${name} Workflow Pack`,
    version:            '0.1.0',
    author,
    description,
    category:           'workflow_pack',
    license:            'MIT',
    permissions:        ['workflows.register', 'executions.read'],
    minimumFlowVersion: '14.0.0',
    dependencies:       {},
    entrypoints:        { main: 'main.js' },
    routes:             [],
    actions:            [],
    events:             [],
    agents:             [],
    widgets:            [],
    migrations:         [],
    tags:               ['workflow'],
  };

  const mainJs = `// ${name} Workflow Pack — generated by FLOW Extension CLI
const { BaseWorkflowPack } = FlowSDK;

class ${_toPascalCase(name)}WorkflowPack extends BaseWorkflowPack {
  workflowDefinitions() {
    return [
      {
        definition: {
          id:          '${wfId}',
          version:     '0.1.0',
          name:        '${name}',
          description: '${description}',
          connectors:  ${JSON.stringify(connectors)},
          steps: ${JSON.stringify(defaultSteps, null, 10).replace(/\n/g, '\n          ')},
        },
        // plannerFn: optional async function(context) — returns modified step params
      },
    ];
  }
}

module.exports = { default: ${_toPascalCase(name)}WorkflowPack };
`;

  return { manifest, files: { 'manifest.json': JSON.stringify(manifest, null, 2), 'main.js': mainJs } };
}

function _toPascalCase(str) {
  return str.replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase())
    .replace(/^./, c => c.toUpperCase());
}
