export default {
  id: 'datadog.get_alert_details',
  version: '1.0.0',
  lifecycle: 'ACTIVE',
  connector: 'datadog',
  category: 'observability',
  displayName: 'Get Datadog Alert Details',
  description: 'Retrieves full details for a Datadog monitor including current state, message, query, and tags. First step in the incident response workflow.',
  icon: 'bell',
  tags: ['datadog', 'alert', 'monitor', 'observability', 'incident'],
  riskLevel: 'LOW',
  approvalPolicy: {
    required: false, minimumApprovers: 0, eligibleRoles: ['MEMBER'],
    timeoutHours: 0, selfApprovalAllowed: true, notifyOnCreate: false, notifyOnResolve: false,
  },
  requiredPermissions: ['MEMBER'],
  requiredScopes: ['monitors:read'],
  executionMode: 'SYNC',
  estimatedDurationMs: 1500,
  timeoutMs: 10000,
  retryStrategy: {
    maxAttempts: 3, backoffType: 'EXPONENTIAL', initialDelayMs: 1000, maxDelayMs: 8000,
    jitterPercent: 10, retryOn: ['TIMEOUT', 'RATE_LIMIT'], noRetryOn: ['MONITOR_NOT_FOUND', 'UNAUTHORIZED'],
  },
  rollbackStrategy: { supported: false, type: 'NONE', description: 'Read-only — no rollback needed.', requiresApproval: false },
  verificationStrategy: { type: 'IMMEDIATE', successCondition: '$.alertId != null' },
  requiredInputs: [
    { name: 'monitorId', type: 'string', description: 'Datadog monitor ID', example: '12345678' },
  ],
  optionalInputs: [],
  outputSchema: {
    type: 'object',
    properties: {
      alertId:   { type: 'string' },
      monitorId: { type: 'string' },
      name:      { type: 'string' },
      status:    { type: 'string', description: 'Overall monitor state (Alert, OK, Warn, No Data)' },
      type:      { type: 'string' },
      message:   { type: 'string' },
      tags:      { type: 'array' },
      query:     { type: 'string' },
      created:   { type: 'string' },
      modified:  { type: 'string' },
    },
  },
  auditMetadata: {
    resourceType: 'datadog_monitor', resourceIdField: 'monitorId', actionVerb: 'read',
    sensitivityLevel: 'INTERNAL', retainForDays: 90, complianceTags: ['SOC2'],
  },
  telemetryMetadata: {
    eventName: 'action.datadog.get_alert_details',
    successMetric: 'flow.action.datadog.get_alert_details.success',
    failureMetric: 'flow.action.datadog.get_alert_details.failure',
    durationMetric: 'flow.action.datadog.get_alert_details.duration_ms',
    dimensions: ['connector', 'workspace_id'],
  },
  relatedActions: ['datadog.mute_monitor', 'datadog.post_event', 'pagerduty.create_incident'],
};
