export default {
  id: 'jira.issue.updated', version: '1.0.0',
  connector: 'jira', category: 'WORK_MANAGEMENT', source: 'webhook',
  displayName: 'Jira Issue Updated', description: 'A Jira issue was updated.',
  priority: 'NORMAL',
  schema: {
    'issue.id':             { type: 'string' },
    'issue.key':            { type: 'string' },
    'issue.fields.summary': { type: 'string' },
    'issue.fields.status.name':    { type: 'string' },
    'issue.fields.priority.name':  { type: 'string' },
    'issue.fields.project.key':    { type: 'string' },
    'changelog.items':             { type: 'array' },
    'user.displayName':            { type: 'string' },
  },
  deduplication: { enabled: true, keyFields: ['sourceEventId'], windowMs: 30_000 },
  ordering:      { guaranteed: false },
  retry:         { maxAttempts: 3, backoffMs: 1_000 },
  security:      { signatureRequired: true, signatureHeader: 'x-hub-signature', algorithm: 'hmac-sha256' },
};
