export default {
  id: 'postgres.backup_database',
  version: '1.0.0',
  lifecycle: 'ACTIVE',
  connector: 'postgres',
  category: 'database',
  displayName: 'Backup PostgreSQL Database',
  description: 'Captures a structural snapshot of the database (table list, sizes, row counts) as a pre-migration safety record. For full pg_dump backups, pair with AWS snapshot or S3 pipeline.',
  icon: 'database',
  tags: ['postgres', 'backup', 'database', 'maintenance', 'compliance'],
  riskLevel: 'LOW',
  approvalPolicy: {
    required: false, minimumApprovers: 0, eligibleRoles: ['MEMBER'],
    timeoutHours: 0, selfApprovalAllowed: true, notifyOnCreate: false, notifyOnResolve: false,
  },
  requiredPermissions: ['MEMBER'],
  requiredScopes: ['pg:select'],
  executionMode: 'ASYNC',
  estimatedDurationMs: 30000,
  timeoutMs: 600000,
  retryStrategy: {
    maxAttempts: 2, backoffType: 'FIXED', initialDelayMs: 5000, maxDelayMs: 5000,
    jitterPercent: 0, retryOn: ['TIMEOUT'], noRetryOn: ['UNAUTHORIZED', 'CONNECTION_FAILED'],
  },
  rollbackStrategy: { supported: false, type: 'NONE', description: 'Backup is a read operation — no rollback needed.', requiresApproval: false },
  verificationStrategy: { type: 'IMMEDIATE', successCondition: '$.backedUpAt != null' },
  requiredInputs: [],
  optionalInputs: [
    { name: 'schema', type: 'string', description: 'Schema to snapshot', example: 'public' },
    { name: 'format', type: 'enum', enum: ['sql', 'json'], description: 'Output format label' },
  ],
  outputSchema: {
    type: 'object',
    properties: {
      backedUpAt:   { type: 'string' },
      databaseName: { type: 'string' },
      totalSize:    { type: 'string' },
      tableCount:   { type: 'number' },
      tables:       { type: 'array' },
    },
  },
  auditMetadata: {
    resourceType: 'postgres_database', resourceIdField: 'schema', actionVerb: 'backed-up',
    sensitivityLevel: 'CONFIDENTIAL', retainForDays: 2190, complianceTags: ['SOC2', 'COMPLIANCE'],
  },
  telemetryMetadata: {
    eventName: 'action.postgres.backup_database',
    successMetric: 'flow.action.postgres.backup_database.success',
    failureMetric: 'flow.action.postgres.backup_database.failure',
    durationMetric: 'flow.action.postgres.backup_database.duration_ms',
    dimensions: ['connector', 'workspace_id'],
  },
  relatedActions: ['postgres.run_migration', 'postgres.vacuum_analyze'],
};
