export default {
  id: 'postgres.vacuum_analyze',
  version: '1.0.0',
  lifecycle: 'ACTIVE',
  connector: 'postgres',
  category: 'database',
  displayName: 'Vacuum and Analyze PostgreSQL',
  description: 'Runs VACUUM ANALYZE to reclaim storage, update query planner statistics, and improve performance. Scheduled as part of the Database Maintenance workflow.',
  icon: 'trash-2',
  tags: ['postgres', 'vacuum', 'analyze', 'maintenance', 'performance'],
  riskLevel: 'MEDIUM',
  approvalPolicy: {
    required: false, minimumApprovers: 0, eligibleRoles: ['ADMIN'],
    timeoutHours: 1, selfApprovalAllowed: true, notifyOnCreate: false, notifyOnResolve: false,
  },
  requiredPermissions: ['ADMIN'],
  requiredScopes: ['pg:execute'],
  executionMode: 'ASYNC',
  estimatedDurationMs: 60000,
  timeoutMs: 3600000,
  retryStrategy: {
    maxAttempts: 1, backoffType: 'NONE', initialDelayMs: 0, maxDelayMs: 0,
    jitterPercent: 0, retryOn: [], noRetryOn: ['UNAUTHORIZED', 'CONNECTION_FAILED'],
  },
  rollbackStrategy: { supported: false, type: 'NONE', description: 'VACUUM is non-transactional — no rollback possible.', requiresApproval: false },
  verificationStrategy: { type: 'IMMEDIATE', successCondition: '$.vacuumed == true' },
  requiredInputs: [],
  optionalInputs: [
    { name: 'table',  type: 'string', description: 'Target table (omit for full database)' },
    { name: 'schema', type: 'string', description: 'Target schema', example: 'public' },
    { name: 'full',   type: 'boolean', description: 'VACUUM FULL (exclusive lock — use only during maintenance window)' },
  ],
  outputSchema: {
    type: 'object',
    properties: {
      vacuumed:   { type: 'boolean' },
      table:      { type: 'string' },
      schema:     { type: 'string' },
      durationMs: { type: 'number' },
      stats:      { type: 'object' },
    },
  },
  auditMetadata: {
    resourceType: 'postgres_table', resourceIdField: 'table', actionVerb: 'vacuumed',
    sensitivityLevel: 'INTERNAL', retainForDays: 365, complianceTags: ['SOC2'],
  },
  telemetryMetadata: {
    eventName: 'action.postgres.vacuum_analyze',
    successMetric: 'flow.action.postgres.vacuum_analyze.success',
    failureMetric: 'flow.action.postgres.vacuum_analyze.failure',
    durationMetric: 'flow.action.postgres.vacuum_analyze.duration_ms',
    dimensions: ['connector', 'workspace_id'],
  },
  relatedActions: ['postgres.backup_database', 'postgres.get_table_stats'],
};
